const IconoInicio = (

    <svg version="1.2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" width="50" height="50">
	<title>iconoInicio</title>
	<defs>
		<image  width="50" height="50" id="img1" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAMAAAAp4XiDAAAAAXNSR0IB2cksfwAAAMBQTFRFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACzsvEAAAAEB0Uk5TAAJXyPjJVm7v/21w9G/ux/dVA2bkLnSU2HWfnqD+/facW5EEkkVGPT71jItS+vlRD7W0DivC8zkqH47h/LgUudGCv78AAAFdSURBVHic7dXLS8NAEAbw/ZImRXtQixV8HERRVCoICuLFP96LD+hBVFB8XurBB1awVFC7psmmu5tM6mzp0T1sPnbyIwkMEwhqIVrR9iXJInkYoncuvQ5lKIJx/MTBxwdhCNIXBSZPDEGbHLEEabIkIyiTITlBGJsQIm8sQoqcMUmByBqDFIqM0WSAsE2fDBSWSckfwjRgCsOAK7QBW/QN+CI1cBDKwEUkBggDvohMt4PQIydG4Qo+EZSchBAhSoEjKQ9Dhngx18+XY6gCbQdRkTJ6RC2a2e+s+yek9/2sOnnujUWqzd6ekIVXFpl6HC2Zjv8vL3wyA7TaojIp5ROXzOI2vi6jySTl2rVKq3cBj/jzVyqt4eGfjIrYnVxIzE7euGeRpQtN6rhhkBWcarKFS6O02KXJOhqaiB2c69ImjlXalWf6uO4fCYOIvWgANETqD1Tax4lK21LKwyT+Am8vnJskkJXSAAAAAElFTkSuQmCC"/>
	</defs>
	<style>
	</style>
	<use id="Background" href="#img1" x="0" y="0"/>
</svg>
    );

export default IconoInicio