import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body> 
          <div className="flex justify-start">
            <div className="h-screen w-32 bg-[#FF533A] opacity-30 rounded-tl-3xl rounded-br-3xl">

            </div>
            {children}
          </div>
        </body>
        
    </html>
  );
}
